### ISSUE TITLE
Suppressing QUIC signaling in favor of RTCP signaling

### ISSUE THREAD

**Issue by gchandok** [mengelbart/rtp-over-quic-draft#117]
Because QUIC relies on certain frames being sent, it is
   not possible to supress QUIC signaling in favor of RTCP signaling,

**In Datagram mode, QUIC flow control and retransmissions are disabled. Also, this draft allows for congestion control to live in the application. So in this situation we should consider disabling ACK frames in the QUIC layer. What function do they provide? Those are probably the most common non-data frames that will be sent at quic layer**

**Comment by SpencerDawkins** [comment]
@SpencerDawkins and @mengelbart are thinking about this, but we THINK there is some level of QUIC signaling that is required in order to look like a working QUIC connection. 

@SpencerDawkins is also remembering that there is a minimal level of RTCP RR reporting that is required for an RTP application to know that the (stateless) RTP session is still active. 

What we NEED to do, is make text about disabling/suppressing/whatever QUIC acks/congestion control and RTCP RR reporting match these two realities. 

@gchandok's observation about congestion control living in the application is important. We should also make sure that the implications that we describe are accurate.

**Comment by SpencerDawkins** [comment]
I'm talking about this issue with @mengelbart, and we think what's needed is a lot more nuanced than "turning RTCP feedback off" or "turning QUIC feedback and related flow control/congestion control off", but we don't think this is a lot of work. We can target the September virtual interim for PR text.

**Comment by aboba** [comment]
While the application can control rate, congestion control is handled by QUIC and can't be safely turned off.
