### ISSUE TITLE
Section 8.1: Timestamp extension requirement

### ISSUE THREAD

**Issue by aboba** [mengelbart/rtp-over-quic-draft#23]
*Editor's note:* An alternative to the hard requirement to use a
      timestamp extension could be to use RTCP, but that would mean,
      that an application has to negotiate RTCP congestion control
      feedback which would then have to be passed to the QUIC congestion
      controller.

**Comment by mengelbart** [comment]
See also #11 

[Section 7](https://www.ietf.org/archive/id/draft-ietf-avtcore-rtp-over-quic-00.html#name-rtcp) explains in detail how information from the QUIC layer can be used to replace RTCP. This is the opposite: we want to use information from RTCP at the QUIC layer. I don't think is useful to add text for this to the document for the following reasons:

- The QUIC congestion controller would depend on the information that is only present at the application layer. If we want to use RTCP (e.g., because timestamps are not available), we can still have congestion control at the application layer as explained in [section 8.2](https://www.ietf.org/archive/id/draft-ietf-avtcore-rtp-over-quic-00.html#section-8.2). If there's no API to disable/manage the QUIC congestion controller, there will likely be no API to pass feedback to it either.
- It would be unclear how the QUIC congestion controller should treat non-RTP data for which we still don't have arrival times.

Should we add an explanation for these problems or just delete the note?

**Comment by aboba** [comment]
I'd delete the note.
