### ISSUE TITLE
Section 9.2: Choosing an appropriate congestion control algorithm

### ISSUE THREAD

**Issue by aboba** [mengelbart/rtp-over-quic-draft#27]
"   *  _Select Congestion Controller_: If congestion control is to be
      implemented at the QUIC connection layer as described in
      Section 8.1, the application must be able to choose an appropriate
      congestion control algorithm."

[BA] Is the need to choose an appropriate algorithm, or to be able to provide information on what characteristics are desired? 
Related: https://github.com/w3c/webtransport/issues/365

**Comment by mengelbart** [comment]
If we decide to state the characteristics in section 8.1 instead of specific algorithms, as discussed in #21 and #36, I think we can leave it to the implementation to decide what the concrete API should look like. I think some QUIC implementations allow choosing between algorithms, but I could also imagine an implementation that lets the application provide information that the QUIC implementation can use to make a decision. Maybe we can change the wording to something like this:

```
If congestion control is to be implemented at the QUIC connection (layer as
described in Section 8.1), the QUIC implementation SHOULD expose an API to
configure the congestion control algorithm.
```

**Comment by aboba** [comment]
In WebTransport, the approach taken has been to provide a "hint" to the QUIC stack which would allow it to select an appropriate congestion control algorithm.  There is no implementation of this yet.  That approach was selected over more detailed configuration of the congestion control algorithm.

**Comment by mengelbart** [comment]
I think that makes sense for WebTransport, but I am not sure we need to be specific about this here. For example, a QUIC implementation that only offers a low latency congestion controller would be fine, even if it does not provide any configuration options to the application. It may be more useful not to phrase this as what the application can control, but rather as how the QUIC implementation must do congestion control.
