### ISSUE TITLE
Consider allowing mixing of QUIC streams and datagrams within RTP sessions

### ISSUE THREAD

**Issue by mengelbart** [mengelbart/rtp-over-quic-draft#41]
> This specification defines two ways of carrying RTP packets in QUIC: 1) using reliable QUIC streams and 2) using unreliable QUIC DATAGRAMs. Every RTP session MUST choose exactly one way of carrying RTP and RTCP packets, different RTP sessions MAY choose different ways

The restriction to choosing exactly one way of carrying packets was added to avoid any unexpected outcomes of sending some RTP packets reliably on QUIC streams and others unreliably in QUIC datagrams.

It may however be desired to allow mixing streams and datagrams to implement partial reliability. For example, a sender may want to send I-frames of a video stream in QUIC streams to ensure reliable delivery, while sending P-frames in datagrams. Another scenario might be to send base layers of a stream using scalable video in QUIC streams and any additional layers in QUIC datagrams.

**Comment by aboba** [comment]
As you mention, there are several use cases for using both QUIC streams and datagrams. 

With SVC, base layer packets may represent a minority of the packets sent (as little as 25 percent with L1T3).  Since the base layer packets depend on each other, and losing one may prevent decoding of subsequent frames at all layers, losing a base layer frame has a high cost (e.g. keyframe generation).  

To avoid this cost, it may be necessary to set partial reliability timers considerably higher for base layer frames than for "discardable" extension layers.  In such a situation, sending base layer frames via frame/stream may not be that different from sending base layer frames over a single unidirectional stream.

**Comment by mengelbart** [comment]
I will bring this up in the meeting today. My general impression is that it is something that we should support. We were hesitant about this in the beginning because we were unsure of the potential problems this could bring up. When experimenting with this setup I ran into a synchronization issue where P-frames arrived before the first I-frame because the implementation prioritized sending datagrams first. This is solvable by having a jitter buffer wait for the first I-frame before passing anything to a decoder, but there may be other problems we haven't thought of yet.

> To avoid this cost, it may be necessary to set partial reliability timers considerably higher for base layer frames than for "discardable" extension layers. In such a situation, sending base layer frames via frame/stream may not be that different from sending base layer frames over a single unidirectional stream.

I think allowing multiple frames/ADUs per frame may be a follow-up discussion of #39?
