### ISSUE TITLE
MAX_STREAMS and frame/stream transport

### ISSUE THREAD

**Issue by aboba** [mengelbart/rtp-over-quic-draft#49]
A recent post on the MoQ list relates to the interaction of MAX_STREAMS and frame/stream transport:
https://mailarchive.ietf.org/arch/msg/moq/hecXJfwaysqbyp85ZUwAT9I5CM0/

Looking at the thread and after having done some experiments, there do appear to be scenarios (e.g. conferencing) where a low MAX_STREAMS limit could be exceeded. 

Related: WebTransport API [Issue 446](https://github.com/w3c/webtransport/issues/446)

**Comment by aboba** [comment]
We have been discussing this issue in the W3C WEBTRANSPORT WG.  Even though the MAX_STREAMS limit is cumulative, web browsers continually update the limit, based on the default maximum number of simultaneous streams on a QUIC connection (100 for Chrome).  The maximum number of simultaneous streams in use is determined by the maximum number of RTP streams and the level of concurrency (e.g. how many QUIC streams are simultaneously in use for each RTP stream).  

There are some scenarios in a limit of 100 simultaneous QUIC streams can be exceeded.  For example, consider a conference in which there are 50 participants and each RTP stream may have 4 QUIC streams in use at a time (e.g. 4 frames in transit).  This might require a limit of 200+ QUIC streams rather than 100.

**Comment by mengelbart** [comment]
The current draft says:

> Opening new streams for new packets MAY implicitly limit the number of packets concurrently in transit because the QUIC receiver provides an upper bound of parallel streams, which it can update using QUIC MAX_STREAMS frames. The number of packets that have to be transmitted concurrently depends on several factors, such as the number of RTP streams within a QUIC connection, the bitrate of the media streams, and the maximum acceptable transmission delay of a given packet. Receivers are responsible for providing senders with enough credit to open new streams for new packets at any time.

As Christian mentioned on the MoQ list, a sender may need additional credits for background streams that are not RTP/RTCP. However, depending on the type of these background streams, they may or may not take some of the credit that is also used for media streams. According to [RFC 9000](https://www.rfc-editor.org/rfc/rfc9000.html#name-controlling-concurrency), `max_streams` of 100 means that a sender can open `100 * 4 + first_stream_id_of_type` streams. `first_stream_id_of_type` can either be `2` if the sender is a client or `3` if it is a server (since we are only using unidirectional streams. If the background data transfer also uses unidirectional streams, it may be necessary to rate limit it to avoid the problem that it takes up all the credit all the time.

The level of concurrency depends on how the sender decides to use streams. The draft currently allows sending any number of packets on a stream or opening new streams at any time, but this may change (see #45). If the receiver knows the properties of the incoming media streams, how many there are, and how the sender uses QUIC streams, it may be able to calculate how often and by how much it must increase the MAX_STREAMS limit.
