### ISSUE TITLE
CC/RA: Explain how to avoid nested congestion controller loops for real time media

### ISSUE THREAD

**Issue by SpencerDawkins** [mengelbart/rtp-over-quic-draft#59]
The current draft says (in "Congestion Control at the Application Layer"), 

> If the application implements full congestion control rather than just a
> bandwidth estimation at the application layer using a congestion controller that
> satisfies the requirements of {{Section 7 of !RFC9002}}, and the connection is
> only used to send real-time media which is subject to the application layer
> congestion control, **it is RECOMMENDED to disable any other congestion control
> that is possibly running at the QUIC layer**. Disabling the additional congestion
> controllers helps to avoid any interference between the different congestion
> controllers.

We have talked about this for at least a couple of years, back when "RTP over QUIC" was still in the QUIC working group, but as I understand it, there's no way to do this now (in a standardized way), and a plain reading of the emphasized text makes me think what's being described would require a QUIC extension. 

I don't care how we actually do this, but we need to write down how to do it!

**Comment by goelvidhi** [comment]
Just noting down the points from my email that needs addressing,

```
Section 8 - This section needs some work IMO with regards to,
1. What spec should one comply to for a real time congestion controller? (I don’t think RFC 9002 is the right compliance for real time CCs)
2. Is bandwidth estimation the only thing needed by media codecs or does QUIC CC need to do more than that?
3. If a real time CC can’t comply to 1., does it need to use both real time CC as well as QUIC CC?
```

**Comment by SpencerDawkins** [comment]
From discussion with @joerg-ott and @mengelbart -

- this is mostly about how a sending application tells a QUIC implementation what general type of congestion controller the QUIC implementation should use (say, NADA vs NewReno, "please DON'T use an h3-optimized congestion controller for media")
- are we expecting the QUIC implementation to figure this out automagically? 
- how badly are h3-optimized congestion controllers going to work for application-limited, interactive applications?
- Mathis work shows that rate-limited RTP rarely encounters QUIC limits that bulk transfer traffic would encounter

**Comment by SpencerDawkins** [comment]
This issue is about the proposal to disable QUIC's congestion controller, since a rate-limiting congestion controller is already in use at the application level.

**Comment by mengelbart** [comment]
I replied to @goelvidhi s comments in #62 .

I agree that the quoted text above is a bit unclear and maybe mixes a few things together that should be separated.

I think as long as a sender complies to the congestion control requirements of QUIC as stated in RFC 9002/RFC 8085, it does not matter how it is implemented We might want to state this explicitly in the introduction to section 8 (see also #62).

The emphasized text above is about disabling one congestion controller when another is active as long as the active congestion controller applies to all outgoing traffic. The idea was to separate between an *RTP layer* and a *QUIC layer* and have the *RTP layer* do congestion control for real-time media. But that only works as long as the *RTP layer* is the only one sending data over the *QUIC layer*. As soon as the QUIC connection is shared between the *RTP layer* and some other datastream, congestion control must be done for both. 

> * this is mostly about how a sending application tells a QUIC implementation what general type of congestion controller the QUIC implementation should use (say, NADA vs NewReno, "please DON'T use an h3-optimized congestion controller for media")
> * are we expecting the QUIC implementation to figure this out automagically?

I don't see how a QUIC extension could help us solve this, but maybe this is rather an API question than a congestion control question?

**Comment by goelvidhi** [comment]
Maybe we can discuss this issue either here or at #62. The general idea is to talk about the 3 options very clearly,
1. CC/rate adaptation at both QUIC and RTP
2. CC at QUIC only with necessary bandwidth estimation (perhaps other things) feedback provided from QUIC to RTP
3. real time rate adaptation only with some compliance to 8085 - this one is tricky. Is there any existing rate adaptation algorithm that does this? If not, then this option is least preferable.

**Comment by mengelbart** [comment]
I think there are multiple dimensions in which we can list different options. The first one is the layer at which congestion control is applied, either at the QUIC implementation layer or the application layer on top of QUIC or both. The second is the kind of congestion control used at both layers, which could for example be optimized for low latency or bulk transfer. And then, we have to distinguish between connections that are used for RTP only and connections that are shared between RTP and other non-RTP streams. Trying to break this down I get to something like this:

### 0. No App CC + No QUIC CC 

  * Forbidden

### 1. App CC + No QUIC CC

* a) If only RTP runs on top of the QUIC connection, this can be any real-time rate adaptation that works well with RTP as long as it satisfies RFC 8085 and ideally also RFC 8836.
* b) If RTP and non-RTP data share a QUIC connection, then all application protocols on top of that connection MUST do their own congestion control. It must be ensured that the result is still compliant with QUIC or RFC 8085 and that each stream receives a fair share of the bandwidth, which might be quite hard to get right.

### 2. No App CC + QUIC CC

* a) If only RTP runs on top of QUIC, the connection should ideally use a low latency congestion control algorithm and expose an estimated bandwidth to the application for codec configuration. This option looks very similar to 1a) above, because it is only an implementation detail where CC is implemented.
* b) If RTP and non-RTP data share a connection, the congestion controller should assign bandwidth shares such that no stream can starve another.

### 3. App CC + QUIC CC

* a) For only RTP, this could be a potential fallback if 1a) and 2a) are not possible, e.g. because QUIC CC cannot do low latency or cannot expose the estimated bandwidth and it cannot be disabled either.
* b) For a shared connection, this could be a potential fallback if 2b) is not possible.

1a) and 2a) are very similar when we have free choice over which algorithms are used. 2b) seems the best choice for sharing connections. 3a) and 3b) don't seem to have any advantages but might be useful if other options are not available.

Regarding real-time rate adaptation that is compliant to RFC 8085: I don't know for sure if the algorithms developed in RMCAT are compliant with RFC 8085, but since they were developed for environments that typically use UDP, I would be surprised if they are not. In any case, even if we can't or don't want to reference those algorithms explicitly, I don't think it should stop us from recommending algorithms that are optimized for low latency in general.

**Comment by SpencerDawkins** [comment]
The discussion that @mengelbart and @goelvidhi have been having for this issue clarifies things quite a bit, even if the discussion mentioned "disabling QUIC CC" from time to time. The parts that don't assume that need to be inserted into the document as guidance, which is what we said at the [February 2023 AVTCORE virtual interim meeting](https://datatracker.ietf.org/meeting/interim-2023-avtcore-01/session/avtcore).
