### ISSUE TITLE
Add MTU vs. extra packet considerations for Acknowledgements when using datagrams

### ISSUE THREAD

**Issue by mengelbart** [mengelbart/rtp-over-quic-draft#85]
QUIC acknowledgment frames can be sent in the same packet as stream or datagram frames, which adds overhead and reduces the maximum size of datagram frames. If a packetizer is configured to produce packets at a fixed maximum MTU, the sender may need to send many extra QUIC packets for acknowledgments. It may be helpful to reference the acknowledgment frequency draft, which could help to reduce the overhead somewhat.

Maybe relevant: https://www.rfc-editor.org/rfc/rfc9000#section-13

**Comment by SpencerDawkins** [comment]
The fundamental problem this issue is pointing to, is that the RTP sender (and receiver) does not have visibility to non-data frames that a QUIC sender may include in an outgoing QUIC packet. So, not just QUIC ACKs. We can provide a description of the trade-offs in the document now, but we probably can't make specific recommendations ("do this, not that") in the document, at least not yet.

**Comment by SpencerDawkins** [comment]
If we find that we are able to make specific recommendations, these recommendations may be added under a follow-up issue.
